spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cowhealth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: cow
    password: cow123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
      timeout: 3000ms

logging:
  level:
    com.cowhealth: INFO
